services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    networks:
      - fraud-net

  redpanda-console:
    image: redpandadata/console:latest
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    networks:
      - fraud-net

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    networks:
      - fraud-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fraud-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - fraud-net

networks:
  fraud-net:
    driver: bridge